name: Terraform Infrastructure Management

on:
  push:
    branches: [ main, master ]
    paths:
      - 'terraform/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'terraform/**'
  # Allow manual triggering of workflow
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
      apply:
        description: 'Apply changes'
        required: true
        default: false
        type: boolean

# Add permissions block for GitHub token
permissions:
  contents: write
  pull-requests: write
  security-events: write
  id-token: write

env:
  TF_VAR_resource_group_name: mvpops-production-rg
  TF_VAR_environment: ${{ github.event.inputs.environment || 'production' }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  TF_VERSION: '1.5.0'

jobs:
  verify-credentials:
    name: 'Verify Azure Credentials'
    runs-on: ubuntu-latest
    steps:
      - name: Verify Azure Environment Variables
        run: |
          if [ -n "$ARM_CLIENT_ID" ]; then
            echo "ARM_CLIENT_ID exists and is set"
            echo "First 4 characters: ${ARM_CLIENT_ID:0:4}..."
          else
            echo "ARM_CLIENT_ID is not set! ❌"
          fi
          
          if [ -n "$ARM_CLIENT_SECRET" ]; then
            echo "ARM_CLIENT_SECRET exists and is set (value masked)"
          else
            echo "ARM_CLIENT_SECRET is not set! ❌"
          fi
          
          if [ -n "$ARM_SUBSCRIPTION_ID" ]; then
            echo "ARM_SUBSCRIPTION_ID exists and is set"
            echo "Value with middle masked: ${ARM_SUBSCRIPTION_ID:0:4}...${ARM_SUBSCRIPTION_ID: -4}"
          else
            echo "ARM_SUBSCRIPTION_ID is not set! ❌"
          fi
          
          if [ -n "$ARM_TENANT_ID" ]; then
            echo "ARM_TENANT_ID exists and is set"
            echo "Value with middle masked: ${ARM_TENANT_ID:0:4}...${ARM_TENANT_ID: -4}"
          else
            echo "ARM_TENANT_ID is not set! ❌"
          fi

  validate:
    name: 'Validate Terraform'
    needs: verify-credentials
    runs-on: ubuntu-latest
    
    # Use the Bash shell
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Validate
        id: validate
        run: |
          terraform init -backend=false
          terraform validate -no-color

      - name: Run tfsec
        uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          sarif_file: tfsec.sarif
          working_directory: terraform
          
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec.sarif

  plan:
    name: 'Plan Terraform Changes'
    needs: validate
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}
    
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Azure Credentials for Plan
        run: |
          echo "Using AZURE_SUBSCRIPTION_ID: ${ARM_SUBSCRIPTION_ID:0:4}...${ARM_SUBSCRIPTION_ID: -4}"
          echo "Using AZURE_TENANT_ID: ${ARM_TENANT_ID:0:4}...${ARM_TENANT_ID: -4}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Create Storage for Terraform State if needed
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Create resource group if it doesn't exist
            az group create --name ${{ env.TF_VAR_resource_group_name }} --location eastus2
            
            # Create storage account if it doesn't exist
            az storage account create \
              --name ${{ secrets.TF_STORAGE_ACCOUNT_NAME }} \
              --resource-group ${{ env.TF_VAR_resource_group_name }} \
              --location eastus2 \
              --sku Standard_LRS \
              --encryption-services blob \
              --kind StorageV2 \
              --allow-blob-public-access false \
              --min-tls-version TLS1_2 || true
              
            # Create container if it doesn't exist
            az storage container create \
              --name ${{ secrets.TF_CONTAINER_NAME }} \
              --account-name ${{ secrets.TF_STORAGE_ACCOUNT_NAME }} \
              --auth-mode login || true

      - name: Terraform Init
        id: init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ env.TF_VAR_resource_group_name }}" \
            -backend-config="storage_account_name=${{ secrets.TF_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ secrets.TF_CONTAINER_NAME }}" \
            -backend-config="key=terraform.tfstate"

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out=tfplan
        
      - name: Archive Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/tfplan
          retention-days: 5

      - name: Comment Plan on PR
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const output = require('child_process').execSync('cd terraform && terraform show -no-color tfplan').toString();
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## Terraform Plan Output\n```terraform\n' + output + '\n```'
            });

  apply:
    name: 'Apply Terraform Changes'
    needs: plan
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.apply == 'true')
    
    # Use the Bash shell
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Azure Credentials for Apply
        run: |
          echo "Using AZURE_SUBSCRIPTION_ID: ${ARM_SUBSCRIPTION_ID:0:4}...${ARM_SUBSCRIPTION_ID: -4}"
          echo "Using AZURE_TENANT_ID: ${ARM_TENANT_ID:0:4}...${ARM_TENANT_ID: -4}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: terraform
          
      - name: Terraform Init
        id: init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ env.TF_VAR_resource_group_name }}" \
            -backend-config="storage_account_name=${{ secrets.TF_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ secrets.TF_CONTAINER_NAME }}" \
            -backend-config="key=terraform.tfstate"

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        
      - name: Generate Terraform Documentation
        run: |
          # Install terraform-docs if needed
          curl -Lo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-$(uname)-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          ./terraform-docs markdown table --output-file README.md --output-mode replace ./

      - name: Update Documentation in Repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Update Terraform documentation [skip ci]"
          file_pattern: terraform/README.md 